AllCops:
  Exclude:
    - db/schema.rb
    - db/migrate/*
  TargetRubyVersion: 2.3
Rails:
  Enabled: true
Style/Documentation:
  Enabled: false
Style/FrozenStringLiteralComment:
  Enabled: false
Style/NumericLiterals:
  Enabled: false
Style/SignalException:
  EnforcedStyle: semantic
Style/VariableNumber:
  EnforcedStyle: snake_case
Metrics/BlockLength:
  Exclude:
    - spec/**/*.rb
